#highlander_says:
#    path: /highlander-says/{threshold<\d+>?50}
#    controller: App\Controller\WeatherController::highlenderSays
#    methods: GET|POST



#highlander_says_guess:
#    path: /highlander-says/{guess}
#    controller: App\Controller\WeatherController::highlenderSaysGuess

